title: Du Juan
email: jdu.xian@gmail.com
description: >
  I am Juan, a Front-end developer at ThoughtWorks in Xi'an, China.
url: "http://dujuan.in/"
twitter_username: dujuan_xian
github_username:  dujuanxian

markdown: kramdown
